name: ai-resume-screening-tool
services:
  - name: backend
    source_dir: /
    github:
      repo: your-username/ai-resume-screening-tool
      branch: main
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
      - key: REDIS_URL
        value: ${redis.REDIS_URL}
      - key: JWT_SECRET
        value: ${JWT_SECRET}
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
    health_check:
      http_path: /health

  - name: frontend
    source_dir: /frontend
    github:
      repo: your-username/ai-resume-screening-tool
      branch: main
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: REACT_APP_API_URL
        value: ${backend.URL}/api/v1
      - key: REACT_APP_WS_URL
        value: ${backend.URL}

databases:
  - name: db
    engine: PG
    version: "15"
    size: db-s-1vcpu-1gb

  - name: redis
    engine: REDIS
    version: "7"
    size: db-s-1vcpu-1gb 